### ISSUE TITLE
GlitchedWriter is not defined

### ISSUE THREAD

**Issue by PubliAlex** [thetarnav/glitched-writer#8]
Hello,

I'm trying to use GlitchedWriter but can't make it works.

I load it using the CDN, like that : 

`<script src="https://cdn.jsdelivr.net/npm/glitched-writer/lib/index.min.js"></script>`

Then I try to instanciate it using the example code : 

```
const Writer = new GlitchedWriter('#glitch-this', {}, (string, writerData) => {
	console.log(`Current string: ${string}`)
	console.log('All the class data:', writerData)
})
```

But I get an error : 

> Uncaught ReferenceError: GlitchedWriter is not defined

Could you please help me to instanciate GlitchedWriter correctly ?

Thank you

**Comment by thetarnav** [comment]
Thanks for the issue.
Unfortunately, the code fetched by jsdelivr wasn't correct, but it should work fine now.
Please use the link [https://cdn.jsdelivr.net/npm/glitched-writer@2.0.22/lib/index.min.js](https://cdn.jsdelivr.net/npm/glitched-writer@2.0.22/lib/index.min.js), for now, because the default one will still point to version 2.0.21 for some time.

Then see if you can access GlitchedWriter:
```js
console.log(GlitchedWriter)
```

If the module is imported, You should see a module object, like this:
![image](https://user-images.githubusercontent.com/24491503/114705497-187c8b00-9d28-11eb-843f-4a9f642a66c3.png)


Now, to create instance, use the create method inside GlitchedWriter. *("new GlitchedWriter()" won't work here)*
```js
const writer = GlitchedWriter.create('#glitch_this')

writer.write('Now, this should work!')
```

Let me know if it helped :)

**Comment by PubliAlex** [comment]
Thank you very much, it works
